in:
  type: file
  path_prefix: example/csv/sample_
  parser:
    charset: UTF-8
    newline: CRLF
    type: csv
    delimiter: ','
    quote: '"'
    escape: '"'
    trim_if_not_quoted: false
    skip_header_lines: 1
    allow_extra_columns: false
    allow_optional_columns: false
    columns:
    - {name: id, type: long}
    - {name: account, type: long}
    - {name: time, type: timestamp, format: '%Y-%m-%d %H:%M:%S'}
    - {name: purchase, type: timestamp, format: '%Y%m%d'}
    - {name: name, type: string}
filters:
  - type: multi_columns
    rules:
      - src: name
#        separator: ' '
#        separator: '\s+'
#        remain: true
        columns:
          - { name: first, type: string }
          - { name: last,  type: string }

out: {type: stdout}
