in:
  type: file
  path_prefix: example/csv/sample.csv
  parser:
    charset: UTF-8
    newline: CRLF
    type: csv
    delimiter: ','
    quote: '"'
    escape: '"'
    trim_if_not_quoted: false
    skip_header_lines: 1
    allow_extra_columns: false
    allow_optional_columns: false
    columns:
    - {name: id, type: long}
    - {name: full_name, type: string}
    - {name: registered_at, type: string }
filters:
  - type: multi_columns
    default_timezone: "Asia/Tokyo"
    rules:
      - src: full_name
        separater: '\s+'
        columns:
          - { name: first_name, type: string }
          - { name: last_name,  type: string }
      - src: registered_at
        columns:
          - { name: register_date, type: timestamp, format: "%Y-%m-%d" }
          - { name: register_time, type: string }
        remain: true
     
out: {type: stdout}
